import { Sofia_Sans } from 'next/font/google';
import './globals.css';

const sofia = Sofia_Sans({ subsets: ['latin'], weight: '600', });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={sofia.className} suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
